#
# © Rolling Array https://rollingarray.co.in/
#
# @summary Deploy KnowledgeN Client app on DEV branch push
# @author code@rollingarray.co.in
#
# Created at     : 2021-05-26 10:42:18 
# Last modified  : 2022-01-31 18:13:06
#

name: Deploy KnowledgeN Client app on DEV branch push

on: 
  push:
    branches: 
      - playground
    # paths:
    #   - 'app/**'
      
jobs:
  web-deploy:

    name: Deploy KnowledgeN Client app
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://knowledgen.dev.rollingarray.co.in/

    # Start stage


    # Use template with parameters
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2


    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    # - name: cd app && ls && pwd
    #   run: ls && cd app && ls && pwd

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build --prod

    - name: Directory Permissions
      run: chmod -R 777 ./www/
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.rollingarray.co.in
        username: rolli3oh@knowledgen.dev.rollingarray.co.in
        password: ;lWJ]cg3J[$N
        local-dir: ./www/
        server-dir: /
        dangerous-clean-slate: true
